/*
 * polygons.c
 *
 *  Created on: Dec 24, 2023
 *      Author: Jakob
 */

#include "polygons.h"

Point left_arrow_polygon[] = {
    { X_BTN_PADDING + 16, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 32 },
    { X_BTN_PADDING + 31, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 47 },
    { X_BTN_PADDING + 31, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 39 },
    { X_BTN_PADDING + 46, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 39 },
    { X_BTN_PADDING + 46, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 24 },
    { X_BTN_PADDING + 31, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 24 },
    { X_BTN_PADDING + 31, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 17 },
};

Point right_arrow_polygon[] = {
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 48, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 32 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 33, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 17 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 33, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 25 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 18, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 25 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 18, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 40 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 33, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 40 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 33, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING - Y_BTN + 47 }
};

Point down_arrow_polygon[] = {
    { X_BTN_PADDING + 32, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 47 },
    { X_BTN_PADDING + 17, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 32 },
    { X_BTN_PADDING + 24, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 32 },
    { X_BTN_PADDING + 24, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 17 },
    { X_BTN_PADDING + 39, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 17 },
    { X_BTN_PADDING + 39, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 32 },
    { X_BTN_PADDING + 47, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 32 }
};

Point play_arrow_polygon[] = {
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 16, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 15 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 47, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 32 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 16, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 49 }
};

Point pause_left_polygon[] = {
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 21, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 14 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 25, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 14 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 25, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 50 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 21, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 50 }
};

Point pause_right_polygon[] = {
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 38, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 14 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 42, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 14 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 42, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 50 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 38, LCD_DEFAULT_HEIGHT - 3 * Y_BTN_PADDING - 3 * Y_BTN + 50 }
};

Point left_rotation_polygon[] = {
    { X_BTN_PADDING + 9, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 17 },
    { X_BTN_PADDING + 17, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 25 },
    { X_BTN_PADDING + 17, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 21 },
    { X_BTN_PADDING + 41, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 21 },
    { X_BTN_PADDING + 41, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 41 },
    { X_BTN_PADDING + 18, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 41 },
    { X_BTN_PADDING + 18, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 49 },
    { X_BTN_PADDING + 49, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 49 },
    { X_BTN_PADDING + 49, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 13 },
    { X_BTN_PADDING + 17, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 13 },
    { X_BTN_PADDING + 17, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 9 }
};

Point right_rotation_polygon[] = {
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 54, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 17 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 46, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 9 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 46, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 13 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 14, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 13 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 14, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 49 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 45, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 49 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 45, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 41 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 22, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 41 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 22, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 21 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 46, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 21 },
    { LCD_DEFAULT_WIDTH - X_BTN_PADDING - X_BTN + 46, LCD_DEFAULT_HEIGHT - Y_BTN_PADDING * 2 - Y_BTN * 2 + 25 }
};

uint8_t polygon_sizes[] = { 7, 11, 7, 11, 7, 3, 4, 4 };

Point* polygons[] = {
    left_arrow_polygon,
    left_rotation_polygon,
    right_arrow_polygon,
    right_rotation_polygon,
    down_arrow_polygon,
    play_arrow_polygon,
    pause_left_polygon,
    pause_right_polygon
};
